// packages/promise-dialog-react-doc/src/views/Test1View.tsx
import React from 'react'
import { useDialog } from 'promise-dialog-react'

interface Props {
  message?: string
}

const Test1View = (props: Props) => {
  const { message = 'default message' } = props
  const { onConfirm } = useDialog()
  const [count, setCount] = React.useState(0)

  onConfirm(({ confirm }) => {
    confirm(count)
  })

  return (
    <div className="">
      <div>props message: {message}</div>
      Test1:count {count}
      <button onClick={() => setCount(count + 1)}>add count</button>
    </div>
  )
}

export default Test1View

// packages/promise-dialog-vue-doc/src/views/Test1View.vue
<template>
  <div class="">
    <div>props message: {{ message }}</div>
    Test1:count {{ count }}
    <button @click="() => count++">add count</button>
  </div>
</template>

<script lang="ts" setup>
import { useDialog } from 'promise-dialog-vue'
import { ref } from 'vue'

interface Props {
  message?: string
}

const props = defineProps<Props>()

const { onConfirm, confirm } = useDialog()
const count = ref(0)

onConfirm(() => {
  confirm(count.value)
})
</script>
<style scpoed>
/* @import url() */
</style>
